name: Generate Traffic

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  visit-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          pnpm install
          pnpm exec playwright install

      - name: Run Traffic Script
        run: pnpm exec tsx scripts/generate-traffic.ts
