name: Generate Traffic

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  generate-traffic:
    runs-on: ubuntu-latest
    env:
      VERCEL_URL: "https://willsather-demo-observability.vercel.app"

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Install Playwright
        run: |
          pnpm exec playwright install

      - name: Run Traffic Script
        run: pnpm exec tsx scripts/generate-traffic.ts
